from enum import Enum


class ClientConfig(Enum):
    MQTT_BROKER_HOST = "MQTT_BROKER_HOST"
    MQTT_BROKER_PORT = "MQTT_BROKER_PORT"
    MQTT_CLIENT_ID = "MQTT_CLIENT_ID"
    MQTT_USER_NAME = "MQTT_USER_NAME"
    MQTT_PASSWORD = "MQTT_PASSWORD"
    BOOTSTRAP_SERVER = "BOOTSTRAP_SERVER"
    TOPIC_MAPPING = "TOPIC_MAPPING"
